swagger: "2.0"
info: {}
basePath: /v1
paths:
  /tooth/:
    post:
      tags:
      - tooth
      description: create tooths
      operationId: ToothController.CreateTooth
      parameters:
      - in: body
        name: body
        description: 添加一个牙齿模型数据
        schema:
          $ref: '#/definitions/models.Tooth'
      responses:
        "200":
          description: succ
        "403":
          description: fail
  /tooth/{id}:
    get:
      tags:
      - tooth
      description: create tooths
      operationId: ToothController.CreateTooth
      parameters:
      - in: path
        name: id
        description: 牙齿id
        type: integer
        format: int64
      responses:
        "200":
          description: succ
        "403":
          description: fail
  /user/:
    post:
      tags:
      - user
      description: create users
      operationId: UserController.CreateUser
      parameters:
      - in: body
        name: body
        description: 注册手机号和密码
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: succ
        "403":
          description: fail
  /user/login:
    post:
      tags:
      - user
      description: Logs user into the system
      operationId: UserController.Login
      parameters:
      - in: body
        name: namewithpwd
        description: 手机号和密码登录
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: '{string} login success'
        "403":
          description: user not exist
definitions:
  models.Profile:
    title: Profile
    type: object
    properties:
      Address:
        type: string
      Age:
        type: integer
        format: int64
      Created:
        type: string
        format: string
      Email:
        type: string
      Gender:
        type: string
      Head:
        type: string
      Updated:
        type: string
        format: string
      Username:
        type: string
  models.Tooth:
    title: Tooth
    type: object
    properties:
      Created:
        type: string
        format: string
      Delete:
        type: boolean
      Id:
        type: integer
        format: int64
      Paramter1:
        type: number
        format: float
      Paramter2:
        type: integer
        format: int64
      Paramter3:
        type: string
      Paramter4:
        type: string
      Paramter5:
        type: string
      Paramter6:
        type: string
      Paramter7:
        type: string
      Paramter8:
        type: string
      Paramter9:
        type: string
      Paramter10:
        type: string
      Updated:
        type: string
        format: string
  models.User:
    title: User
    type: object
    properties:
      Created:
        type: string
        format: string
      Id:
        type: integer
        format: int64
      Password:
        type: string
      Phone:
        type: string
      Profile:
        $ref: '#/definitions/models.Profile'
      Updated:
        type: string
        format: string
